#pragma once
#include "_impl/wrappers.h"
#include <GL/gl.h>
namespace gl {
struct context {
  static constexpr auto error_message = "not in GL context";
};
}  // namespace gl

WRAP_FNC(gl, CullFace, void, (GLenum mode))
WRAP_FNC(gl, FrontFace, void, (GLenum mode))
WRAP_FNC(gl, Hint, void, (GLenum target, GLenum mode))
WRAP_FNC(gl, LineWidth, void, (GLfloat width))
WRAP_FNC(gl, PointSize, void, (GLfloat size))
WRAP_FNC(gl, PolygonMode, void, (GLenum face, GLenum mode))
WRAP_FNC(gl, Scissor, void, (GLint x, GLint y, GLsizei width, GLsizei height))
WRAP_FNC(gl, TexParameterf, void, (GLenum target, GLenum pname, GLfloat param))
WRAP_FNC(gl, TexParameterfv, void, (GLenum target, GLenum pname, const GLfloat* params))
WRAP_FNC(gl, TexParameteri, void, (GLenum target, GLenum pname, GLint param))
WRAP_FNC(gl, TexParameteriv, void, (GLenum target, GLenum pname, const GLint* params))
WRAP_FNC(gl,
         TexImage1D,
         void,
         (GLenum target,
          GLint level,
          GLint internalformat,
          GLsizei width,
          GLint border,
          GLenum format,
          GLenum type,
          const void* pixels))
WRAP_FNC(gl,
         TexImage2D,
         void,
         (GLenum target,
          GLint level,
          GLint internalformat,
          GLsizei width,
          GLsizei height,
          GLint border,
          GLenum format,
          GLenum type,
          const void* pixels))
WRAP_FNC(gl, DrawBuffer, void, (GLenum buf))
WRAP_FNC(gl, Clear, void, (GLbitfield mask))
WRAP_FNC(gl, ClearColor, void, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
WRAP_FNC(gl, ClearStencil, void, (GLint s))
WRAP_FNC(gl, ClearDepth, void, (GLdouble depth))
WRAP_FNC(gl, StencilMask, void, (GLuint mask))
WRAP_FNC(gl, ColorMask, void, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))
WRAP_FNC(gl, DepthMask, void, (GLboolean flag))
WRAP_FNC(gl, Disable, void, (GLenum cap))
WRAP_FNC(gl, Enable, void, (GLenum cap))
WRAP_FNC(gl, Finish, void, ())
WRAP_FNC(gl, Flush, void, ())
WRAP_FNC(gl, BlendFunc, void, (GLenum sfactor, GLenum dfactor))
WRAP_FNC(gl, LogicOp, void, (GLenum opcode))
WRAP_FNC(gl, StencilFunc, void, (GLenum func, GLint ref, GLuint mask))
WRAP_FNC(gl, StencilOp, void, (GLenum fail, GLenum zfail, GLenum zpass))
WRAP_FNC(gl, DepthFunc, void, (GLenum func))
WRAP_FNC(gl, PixelStoref, void, (GLenum pname, GLfloat param))
WRAP_FNC(gl, PixelStorei, void, (GLenum pname, GLint param))
WRAP_FNC(gl, ReadBuffer, void, (GLenum src))
WRAP_FNC(
    gl,
    ReadPixels,
    void,
    (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels))
WRAP_FNC(gl, GetBooleanv, void, (GLenum pname, GLboolean* data))
WRAP_FNC(gl, GetDoublev, void, (GLenum pname, GLdouble* data))
WRAP_FNC(gl, GetError, GLenum, ())
WRAP_FNC(gl, GetFloatv, void, (GLenum pname, GLfloat* data))
WRAP_FNC(gl, GetIntegerv, void, (GLenum pname, GLint* data))
WRAP_FNC(gl,
         GetTexImage,
         void,
         (GLenum target, GLint level, GLenum format, GLenum type, void* pixels))
WRAP_FNC(gl, GetTexParameterfv, void, (GLenum target, GLenum pname, GLfloat* params))
WRAP_FNC(gl, GetTexParameteriv, void, (GLenum target, GLenum pname, GLint* params))
WRAP_FNC(gl,
         GetTexLevelParameterfv,
         void,
         (GLenum target, GLint level, GLenum pname, GLfloat* params))
WRAP_FNC(gl,
         GetTexLevelParameteriv,
         void,
         (GLenum target, GLint level, GLenum pname, GLint* params))
WRAP_FNC(gl, IsEnabled, GLboolean, (GLenum cap))
WRAP_FNC(gl, DepthRange, void, (GLdouble n, GLdouble f))
WRAP_FNC(gl, Viewport, void, (GLint x, GLint y, GLsizei width, GLsizei height))
WRAP_FNC(gl, GetString, const GLubyte*, (GLenum name))

WRAP_FNC(gl, Begin, void, (GLenum mode))
WRAP_FNC(gl, End, void, ())
WRAP_FNC(gl, Vertex2d, void, (GLdouble x, GLdouble y))
WRAP_FNC(gl, Vertex2f, void, (GLfloat x, GLfloat y))
WRAP_FNC(gl, Vertex2i, void, (GLint x, GLint y))
WRAP_FNC(gl, Vertex2s, void, (GLshort x, GLshort y))
WRAP_FNC(gl, Vertex3d, void, (GLdouble x, GLdouble y, GLdouble z))
WRAP_FNC(gl, Vertex3f, void, (GLfloat x, GLfloat y, GLfloat z))
WRAP_FNC(gl, Vertex3i, void, (GLint x, GLint y, GLint z))
WRAP_FNC(gl, Vertex3s, void, (GLshort x, GLshort y, GLshort z))
WRAP_FNC(gl, Vertex4d, void, (GLdouble x, GLdouble y, GLdouble z, GLdouble w))
WRAP_FNC(gl, Vertex4f, void, (GLfloat x, GLfloat y, GLfloat z, GLfloat w))
WRAP_FNC(gl, Vertex4i, void, (GLint x, GLint y, GLint z, GLint w))
WRAP_FNC(gl, Vertex4s, void, (GLshort x, GLshort y, GLshort z, GLshort w))
WRAP_FNC(gl, Vertex2dv, void, (const GLdouble* v))
WRAP_FNC(gl, Vertex2fv, void, (const GLfloat* v))
WRAP_FNC(gl, Vertex2iv, void, (const GLint* v))
WRAP_FNC(gl, Vertex2sv, void, (const GLshort* v))
WRAP_FNC(gl, Vertex3dv, void, (const GLdouble* v))
WRAP_FNC(gl, Vertex3fv, void, (const GLfloat* v))
WRAP_FNC(gl, Vertex3iv, void, (const GLint* v))
WRAP_FNC(gl, Vertex3sv, void, (const GLshort* v))
WRAP_FNC(gl, Vertex4dv, void, (const GLdouble* v))
WRAP_FNC(gl, Vertex4fv, void, (const GLfloat* v))
WRAP_FNC(gl, Vertex4iv, void, (const GLint* v))
WRAP_FNC(gl, Vertex4sv, void, (const GLshort* v))
WRAP_FNC(gl, Normal3b, void, (GLbyte nx, GLbyte ny, GLbyte nz))
WRAP_FNC(gl, Normal3d, void, (GLdouble nx, GLdouble ny, GLdouble nz))
WRAP_FNC(gl, Normal3f, void, (GLfloat nx, GLfloat ny, GLfloat nz))
WRAP_FNC(gl, Normal3i, void, (GLint nx, GLint ny, GLint nz))
WRAP_FNC(gl, Normal3s, void, (GLshort nx, GLshort ny, GLshort nz))
WRAP_FNC(gl, Normal3bv, void, (const GLbyte* v))
WRAP_FNC(gl, Normal3dv, void, (const GLdouble* v))
WRAP_FNC(gl, Normal3fv, void, (const GLfloat* v))
WRAP_FNC(gl, Normal3iv, void, (const GLint* v))
WRAP_FNC(gl, Normal3sv, void, (const GLshort* v))
WRAP_FNC(gl, Indexd, void, (GLdouble c))
WRAP_FNC(gl, Indexf, void, (GLfloat c))
WRAP_FNC(gl, Indexi, void, (GLint c))
WRAP_FNC(gl, Indexs, void, (GLshort c))
WRAP_FNC(gl, Indexub, void, (GLubyte c))
WRAP_FNC(gl, Indexdv, void, (const GLdouble* c))
WRAP_FNC(gl, Indexfv, void, (const GLfloat* c))
WRAP_FNC(gl, Indexiv, void, (const GLint* c))
WRAP_FNC(gl, Indexsv, void, (const GLshort* c))
WRAP_FNC(gl, Indexubv, void, (const GLubyte* c))
WRAP_FNC(gl, Color3b, void, (GLbyte red, GLbyte green, GLbyte blue))
WRAP_FNC(gl, Color3d, void, (GLdouble red, GLdouble green, GLdouble blue))
WRAP_FNC(gl, Color3f, void, (GLfloat red, GLfloat green, GLfloat blue))
WRAP_FNC(gl, Color3i, void, (GLint red, GLint green, GLint blue))
WRAP_FNC(gl, Color3s, void, (GLshort red, GLshort green, GLshort blue))
WRAP_FNC(gl, Color3ub, void, (GLubyte red, GLubyte green, GLubyte blue))
WRAP_FNC(gl, Color3ui, void, (GLuint red, GLuint green, GLuint blue))
WRAP_FNC(gl, Color3us, void, (GLushort red, GLushort green, GLushort blue))
WRAP_FNC(gl, Color4b, void, (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha))
WRAP_FNC(gl, Color4d, void, (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha))
WRAP_FNC(gl, Color4f, void, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
WRAP_FNC(gl, Color4i, void, (GLint red, GLint green, GLint blue, GLint alpha))
WRAP_FNC(gl, Color4s, void, (GLshort red, GLshort green, GLshort blue, GLshort alpha))
WRAP_FNC(gl, Color4ub, void, (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha))
WRAP_FNC(gl, Color4ui, void, (GLuint red, GLuint green, GLuint blue, GLuint alpha))
WRAP_FNC(gl, Color4us, void, (GLushort red, GLushort green, GLushort blue, GLushort alpha))
WRAP_FNC(gl, Color3bv, void, (const GLbyte* v))
WRAP_FNC(gl, Color3dv, void, (const GLdouble* v))
WRAP_FNC(gl, Color3fv, void, (const GLfloat* v))
WRAP_FNC(gl, Color3iv, void, (const GLint* v))
WRAP_FNC(gl, Color3sv, void, (const GLshort* v))
WRAP_FNC(gl, Color3ubv, void, (const GLubyte* v))
WRAP_FNC(gl, Color3uiv, void, (const GLuint* v))
WRAP_FNC(gl, Color3usv, void, (const GLushort* v))
WRAP_FNC(gl, Color4bv, void, (const GLbyte* v))
WRAP_FNC(gl, Color4dv, void, (const GLdouble* v))
WRAP_FNC(gl, Color4fv, void, (const GLfloat* v))
WRAP_FNC(gl, Color4iv, void, (const GLint* v))
WRAP_FNC(gl, Color4sv, void, (const GLshort* v))
WRAP_FNC(gl, Color4ubv, void, (const GLubyte* v))
WRAP_FNC(gl, Color4uiv, void, (const GLuint* v))
WRAP_FNC(gl, Color4usv, void, (const GLushort* v))
WRAP_FNC(gl, TexCoord1d, void, (GLdouble s))
WRAP_FNC(gl, TexCoord1f, void, (GLfloat s))
WRAP_FNC(gl, TexCoord1i, void, (GLint s))
WRAP_FNC(gl, TexCoord1s, void, (GLshort s))
WRAP_FNC(gl, TexCoord2d, void, (GLdouble s, GLdouble t))
WRAP_FNC(gl, TexCoord2f, void, (GLfloat s, GLfloat t))
WRAP_FNC(gl, TexCoord2i, void, (GLint s, GLint t))
WRAP_FNC(gl, TexCoord2s, void, (GLshort s, GLshort t))
WRAP_FNC(gl, TexCoord3d, void, (GLdouble s, GLdouble t, GLdouble r))
WRAP_FNC(gl, TexCoord3f, void, (GLfloat s, GLfloat t, GLfloat r))
WRAP_FNC(gl, TexCoord3i, void, (GLint s, GLint t, GLint r))
WRAP_FNC(gl, TexCoord3s, void, (GLshort s, GLshort t, GLshort r))
WRAP_FNC(gl, TexCoord4d, void, (GLdouble s, GLdouble t, GLdouble r, GLdouble q))
WRAP_FNC(gl, TexCoord4f, void, (GLfloat s, GLfloat t, GLfloat r, GLfloat q))
WRAP_FNC(gl, TexCoord4i, void, (GLint s, GLint t, GLint r, GLint q))
WRAP_FNC(gl, TexCoord4s, void, (GLshort s, GLshort t, GLshort r, GLshort q))
WRAP_FNC(gl, TexCoord1dv, void, (const GLdouble* v))
WRAP_FNC(gl, TexCoord1fv, void, (const GLfloat* v))
WRAP_FNC(gl, TexCoord1iv, void, (const GLint* v))
WRAP_FNC(gl, TexCoord1sv, void, (const GLshort* v))
WRAP_FNC(gl, TexCoord2dv, void, (const GLdouble* v))
WRAP_FNC(gl, TexCoord2fv, void, (const GLfloat* v))
WRAP_FNC(gl, TexCoord2iv, void, (const GLint* v))
WRAP_FNC(gl, TexCoord2sv, void, (const GLshort* v))
WRAP_FNC(gl, TexCoord3dv, void, (const GLdouble* v))
WRAP_FNC(gl, TexCoord3fv, void, (const GLfloat* v))
WRAP_FNC(gl, TexCoord3iv, void, (const GLint* v))
WRAP_FNC(gl, TexCoord3sv, void, (const GLshort* v))
WRAP_FNC(gl, TexCoord4dv, void, (const GLdouble* v))
WRAP_FNC(gl, TexCoord4fv, void, (const GLfloat* v))
WRAP_FNC(gl, TexCoord4iv, void, (const GLint* v))
WRAP_FNC(gl, TexCoord4sv, void, (const GLshort* v))
WRAP_FNC(gl, RasterPos2d, void, (GLdouble x, GLdouble y))
WRAP_FNC(gl, RasterPos2f, void, (GLfloat x, GLfloat y))
WRAP_FNC(gl, RasterPos2i, void, (GLint x, GLint y))
WRAP_FNC(gl, RasterPos2s, void, (GLshort x, GLshort y))
WRAP_FNC(gl, RasterPos3d, void, (GLdouble x, GLdouble y, GLdouble z))
WRAP_FNC(gl, RasterPos3f, void, (GLfloat x, GLfloat y, GLfloat z))
WRAP_FNC(gl, RasterPos3i, void, (GLint x, GLint y, GLint z))
WRAP_FNC(gl, RasterPos3s, void, (GLshort x, GLshort y, GLshort z))
WRAP_FNC(gl, RasterPos4d, void, (GLdouble x, GLdouble y, GLdouble z, GLdouble w))
WRAP_FNC(gl, RasterPos4f, void, (GLfloat x, GLfloat y, GLfloat z, GLfloat w))
WRAP_FNC(gl, RasterPos4i, void, (GLint x, GLint y, GLint z, GLint w))
WRAP_FNC(gl, RasterPos4s, void, (GLshort x, GLshort y, GLshort z, GLshort w))
WRAP_FNC(gl, RasterPos2dv, void, (const GLdouble* v))
WRAP_FNC(gl, RasterPos2fv, void, (const GLfloat* v))
WRAP_FNC(gl, RasterPos2iv, void, (const GLint* v))
WRAP_FNC(gl, RasterPos2sv, void, (const GLshort* v))
WRAP_FNC(gl, RasterPos3dv, void, (const GLdouble* v))
WRAP_FNC(gl, RasterPos3fv, void, (const GLfloat* v))
WRAP_FNC(gl, RasterPos3iv, void, (const GLint* v))
WRAP_FNC(gl, RasterPos3sv, void, (const GLshort* v))
WRAP_FNC(gl, RasterPos4dv, void, (const GLdouble* v))
WRAP_FNC(gl, RasterPos4fv, void, (const GLfloat* v))
WRAP_FNC(gl, RasterPos4iv, void, (const GLint* v))
WRAP_FNC(gl, RasterPos4sv, void, (const GLshort* v))
WRAP_FNC(gl, Rectd, void, (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2))
WRAP_FNC(gl, Rectf, void, (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2))
WRAP_FNC(gl, Recti, void, (GLint x1, GLint y1, GLint x2, GLint y2))
WRAP_FNC(gl, Rects, void, (GLshort x1, GLshort y1, GLshort x2, GLshort y2))
WRAP_FNC(gl, Rectdv, void, (const GLdouble* v1, const GLdouble* v2))
WRAP_FNC(gl, Rectfv, void, (const GLfloat* v1, const GLfloat* v2))
WRAP_FNC(gl, Rectiv, void, (const GLint* v1, const GLint* v2))
WRAP_FNC(gl, Rectsv, void, (const GLshort* v1, const GLshort* v2))