#pragma once
#include "_impl/wrappers.h"
#include <GL/freeglut.h>

namespace glut {
struct context {
  static constexpr auto error_message = "not in glut context";
};
}  // namespace glut

WRAP_FNC(glut, Init, void, (int* pargc, char** argv))
WRAP_FNC(glut, InitWindowPosition, void, (int x, int y))
WRAP_FNC(glut, InitWindowSize, void, (int width, int height))
WRAP_FNC(glut, InitDisplayMode, void, (unsigned int displayMode))
WRAP_FNC(glut, InitDisplayString, void, (const char* displayMode))
WRAP_FNC(glut, MainLoop, void, ())
WRAP_FNC(glut, CreateWindow, int, (const char* title))
WRAP_FNC(glut, CreateSubWindow, int, (int window, int x, int y, int width, int height))
WRAP_FNC(glut, DestroyWindow, void, (int window))
WRAP_FNC(glut, SetWindow, void, (int window))
WRAP_FNC(glut, GetWindow, int, ())
WRAP_FNC(glut, SetWindowTitle, void, (const char* title))
WRAP_FNC(glut, SetIconTitle, void, (const char* title))
WRAP_FNC(glut, ReshapeWindow, void, (int width, int height))
WRAP_FNC(glut, PositionWindow, void, (int x, int y))
WRAP_FNC(glut, ShowWindow, void, ())
WRAP_FNC(glut, HideWindow, void, ())
WRAP_FNC(glut, IconifyWindow, void, ())
WRAP_FNC(glut, PushWindow, void, ())
WRAP_FNC(glut, PopWindow, void, ())
WRAP_FNC(glut, FullScreen, void, ())
WRAP_FNC(glut, PostWindowRedisplay, void, (int window))
WRAP_FNC(glut, PostRedisplay, void, ())
WRAP_FNC(glut, SwapBuffers, void, ())
WRAP_FNC(glut, WarpPointer, void, (int x, int y))
WRAP_FNC(glut, SetCursor, void, (int cursor))
WRAP_FNC(glut, EstablishOverlay, void, ())
WRAP_FNC(glut, RemoveOverlay, void, ())
WRAP_FNC(glut, UseLayer, void, (GLenum layer))
WRAP_FNC(glut, PostOverlayRedisplay, void, ())
WRAP_FNC(glut, PostWindowOverlayRedisplay, void, (int window))
WRAP_FNC(glut, ShowOverlay, void, ())
WRAP_FNC(glut, HideOverlay, void, ())
WRAP_FNC(glut, CreateMenu, int, (void (*callback)(int menu)))
WRAP_FNC(glut, DestroyMenu, void, (int menu))
WRAP_FNC(glut, GetMenu, int, ())
WRAP_FNC(glut, SetMenu, void, (int menu))
WRAP_FNC(glut, AddMenuEntry, void, (const char* label, int value))
WRAP_FNC(glut, AddSubMenu, void, (const char* label, int subMenu))
WRAP_FNC(glut, ChangeToMenuEntry, void, (int item, const char* label, int value))
WRAP_FNC(glut, ChangeToSubMenu, void, (int item, const char* label, int value))
WRAP_FNC(glut, RemoveMenuItem, void, (int item))
WRAP_FNC(glut, AttachMenu, void, (int button))
WRAP_FNC(glut, DetachMenu, void, (int button))
WRAP_FNC(glut, TimerFunc, void, (unsigned int time, void (*callback)(int), int value))
WRAP_FNC(glut, IdleFunc, void, (void (*callback)()))
WRAP_FNC(glut, KeyboardFunc, void, (void (*callback)(unsigned char, int, int)))
WRAP_FNC(glut, SpecialFunc, void, (void (*callback)(int, int, int)))
WRAP_FNC(glut, ReshapeFunc, void, (void (*callback)(int, int)))
WRAP_FNC(glut, VisibilityFunc, void, (void (*callback)(int)))
WRAP_FNC(glut, DisplayFunc, void, (void (*callback)()))
WRAP_FNC(glut, MouseFunc, void, (void (*callback)(int, int, int, int)))
WRAP_FNC(glut, MotionFunc, void, (void (*callback)(int, int)))
WRAP_FNC(glut, PassiveMotionFunc, void, (void (*callback)(int, int)))
WRAP_FNC(glut, EntryFunc, void, (void (*callback)(int)))
WRAP_FNC(glut, KeyboardUpFunc, void, (void (*callback)(unsigned char, int, int)))
WRAP_FNC(glut, SpecialUpFunc, void, (void (*callback)(int, int, int)))
WRAP_FNC(glut,
         JoystickFunc,
         void,
         (void (*callback)(unsigned int, int, int, int), int pollInterval))
WRAP_FNC(glut, MenuStateFunc, void, (void (*callback)(int)))
WRAP_FNC(glut, MenuStatusFunc, void, (void (*callback)(int, int, int)))
WRAP_FNC(glut, OverlayDisplayFunc, void, (void (*callback)()))
WRAP_FNC(glut, WindowStatusFunc, void, (void (*callback)(int)))
WRAP_FNC(glut, SpaceballMotionFunc, void, (void (*callback)(int, int, int)))
WRAP_FNC(glut, SpaceballRotateFunc, void, (void (*callback)(int, int, int)))
WRAP_FNC(glut, SpaceballButtonFunc, void, (void (*callback)(int, int)))
WRAP_FNC(glut, ButtonBoxFunc, void, (void (*callback)(int, int)))
WRAP_FNC(glut, DialsFunc, void, (void (*callback)(int, int)))
WRAP_FNC(glut, TabletMotionFunc, void, (void (*callback)(int, int)))
WRAP_FNC(glut, TabletButtonFunc, void, (void (*callback)(int, int, int, int)))
WRAP_FNC(glut, Get, int, (GLenum query))
WRAP_FNC(glut, DeviceGet, int, (GLenum query))
WRAP_FNC(glut, GetModifiers, int, ())
WRAP_FNC(glut, LayerGet, int, (GLenum query))
WRAP_FNC(glut, BitmapCharacter, void, (void* font, int character))
WRAP_FNC(glut, BitmapWidth, int, (void* font, int character))
WRAP_FNC(glut, StrokeCharacter, void, (void* font, int character))
WRAP_FNC(glut, StrokeWidth, int, (void* font, int character))
WRAP_FNC(glut, StrokeWidthf, GLfloat, (void* font, int character))
WRAP_FNC(glut, BitmapLength, int, (void* font, const unsigned char* string))
WRAP_FNC(glut, StrokeLength, int, (void* font, const unsigned char* string))
WRAP_FNC(glut, StrokeLengthf, GLfloat, (void* font, const unsigned char* string))
WRAP_FNC(glut, WireCube, void, (double size))
WRAP_FNC(glut, SolidCube, void, (double size))
WRAP_FNC(glut, WireSphere, void, (double radius, GLint slices, GLint stacks))
WRAP_FNC(glut, SolidSphere, void, (double radius, GLint slices, GLint stacks))
WRAP_FNC(glut, WireCone, void, (double base, double height, GLint slices, GLint stacks))
WRAP_FNC(glut, SolidCone, void, (double base, double height, GLint slices, GLint stacks))
WRAP_FNC(glut, WireTorus, void, (double innerRadius, double outerRadius, GLint sides, GLint rings))
WRAP_FNC(glut, SolidTorus, void, (double innerRadius, double outerRadius, GLint sides, GLint rings))
WRAP_FNC(glut, WireDodecahedron, void, ())
WRAP_FNC(glut, SolidDodecahedron, void, ())
WRAP_FNC(glut, WireOctahedron, void, ())
WRAP_FNC(glut, SolidOctahedron, void, ())
WRAP_FNC(glut, WireTetrahedron, void, ())
WRAP_FNC(glut, SolidTetrahedron, void, ())
WRAP_FNC(glut, WireIcosahedron, void, ())
WRAP_FNC(glut, SolidIcosahedron, void, ())
WRAP_FNC(glut, WireTeapot, void, (double size))
WRAP_FNC(glut, SolidTeapot, void, (double size))
WRAP_FNC(glut, GameModeString, void, (const char* string))
WRAP_FNC(glut, EnterGameMode, int, ())
WRAP_FNC(glut, LeaveGameMode, void, ())
WRAP_FNC(glut, GameModeGet, int, (GLenum query))
WRAP_FNC(glut, VideoResizeGet, int, (GLenum query))
WRAP_FNC(glut, SetupVideoResizing, void, ())
WRAP_FNC(glut, StopVideoResizing, void, ())
WRAP_FNC(glut, VideoResize, void, (int x, int y, int width, int height))
WRAP_FNC(glut, VideoPan, void, (int x, int y, int width, int height))
WRAP_FNC(glut, SetColor, void, (int color, GLfloat red, GLfloat green, GLfloat blue))
WRAP_FNC(glut, GetColor, GLfloat, (int color, int component))
WRAP_FNC(glut, CopyColormap, void, (int window))
WRAP_FNC(glut, IgnoreKeyRepeat, void, (int ignore))
WRAP_FNC(glut, SetKeyRepeat, void, (int repeatMode))
WRAP_FNC(glut, ForceJoystickFunc, void, ())
WRAP_FNC(glut, ExtensionSupported, int, (const char* extension))
WRAP_FNC(glut, ReportErrors, void, ())